name: Newman Tests with HTML Report

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-api-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Newman and HTMLExtra Reporter
      run: |
        npm install -g newman
        npm install -g newman-reporter-htmlextra

    - name: Run Newman with HTMLExtra Report
      run: |
        newman run "Restful Booker BVT.postman_collection.json" \
          -e "Production.postman_environment.json" \
          -r htmlextra \
          --reporter-htmlextra-export newman/htmlreport.html

    - name: Upload HTML Report Artifact
      uses: actions/upload-artifact@v3
      with:
        name: newman-html-report
        path: newman/htmlreport.html
